//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Animales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_Animales()
        {
            this.C_Adopciones = new HashSet<C_Adopciones>();
        }
    
        public int IdAnimal { get; set; }
        public Nullable<int> IdTamano { get; set; }
        public Nullable<int> IdTemperamento { get; set; }
        public string nombre { get; set; }
        public string especie { get; set; }
        public string raza { get; set; }
        public string sexo { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public string otrasSenas { get; set; }
        public string padecimientos { get; set; }
        public string ImagenURL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Adopciones> C_Adopciones { get; set; }
        public virtual C_Tamanos C_Tamanos { get; set; }
        public virtual C_Temperamentos C_Temperamentos { get; set; }
    }
}
