//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_CasaCuna
    {
        public int IdCasaCuna { get; set; }
        public Nullable<int> IdPersona { get; set; }
        public string Metros { get; set; }
        public Nullable<bool> PropiedadCercada { get; set; }
        public Nullable<int> OtrasMascotas { get; set; }
        public Nullable<int> CapacidadDisponible { get; set; }
        public string DescripcionPropiedad { get; set; }
    
        public virtual C_Persona C_Persona { get; set; }
    }
}
