//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_Persona()
        {
            this.C_Adopciones = new HashSet<C_Adopciones>();
            this.C_CasaCuna = new HashSet<C_CasaCuna>();
        }
    
        public int IdPersona { get; set; }
        public Nullable<int> IdDistrito { get; set; }
        public Nullable<int> IdProvincia { get; set; }
        public Nullable<int> IdCanton { get; set; }
        public string nombrePersona { get; set; }
        public string primerApellido { get; set; }
        public string segundoApellido { get; set; }
        public string cedula { get; set; }
        public string correo { get; set; }
        public string sexo { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public string estadoCivil { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Adopciones> C_Adopciones { get; set; }
        public virtual C_Canton C_Canton { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_CasaCuna> C_CasaCuna { get; set; }
        public virtual C_Distrito C_Distrito { get; set; }
        public virtual C_Provincia C_Provincia { get; set; }
    }
}
