//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Usuarios
    {
        public int IdUsuario { get; set; }
        public Nullable<int> IdRol { get; set; }
        public string Usuario { get; set; }
        public string Contrasena { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        public virtual C_Roles C_Roles { get; set; }
    }
}
